### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [LisandroHernan/ProyectoFinalBioinf2017-II#2]
"*he tenido algunos problemas con la instalación del software, lo estoy haciendo en un contenedor de docker* 

¿Cuáles problemas? ¿Ya se solucionó? En un contenedor de docker todo ya debería estar instalado.
 
Los paquetes de R que mencionas son buenos y seguro que te servirán. También revisa adegenet.

**Comment by LisandroHernan** [comment]
Hola Alicia, una disculpa creo que no di click a comment y no se envió el comentario anterior, el problema es que estoy trabajando en windows y al querer correr o reinstalar blast en un contenedor de Docker salía un mensaje que el problema era de Daemon.... Ya lo solucioné debido a que reínstale Docker, estoy en proceso de correr mis datos. Saludos

**Comment by AliciaMstt** [comment]
Bien

**Comment by LisandroHernan** [comment]
Hola Alicia, he estado intentanto leer mis datos pero al momento de colocar la línea de comando e intentar correrla, no lee mi archivo con mis secuencias para hacerle el blast.

Monte el volumen en Docker y lo corrí con bioconteiners/blast pero no puede leer  mi archivo donde esta mis secuencias.
El mensaje que sale es:
Command line argument error: Argument "query". File is not accessible:  `Padinablast'
